# Use a base image with Go 1.23.1 installed
FROM golang:1.23.1-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code into the container
COPY servidor/ .

# Build the Go application
RUN go build -o servidor ./servidor.go

# Expose the port the server will run on
EXPOSE 8080

# Command to run the server
CMD ["./servidor"]